# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
url: https://wernull.com
title: wernull
author: Kyle Werner
description: Tube amplifiers and tech blog by Kyle Werner

email: contact@wernull.com
baseurl: "" # the subpath of your site, e.g. /blog

date_format: "%e %B %Y"
time_format: ''

root: 
permalink: /:year/:month/:title/
source: source
destination: public
code_dir: downloads/code
category_dir: categories
sass: 
  implementation: sass-embedded
  sass_dir: _sass
# markdown: rdiscount
# rdiscount:
#   extensions:
#     - autolink
#     - footnotes
#     - smart
highlighter: pygments # default python pygments have been replaced by pygments.rb

paginate: 5          # Posts per page on the blog index
paginate_path: "posts/:num"  # Directory base for pagination URLs eg. /posts/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"

subscribe_rss: /feed

titlecase: true   

# Build settings
plugins:
  - jekyll-feed
  - jekyll-gist

instagram_user: wernull
twitter_user: wernull
linkedin_user: wernull
github_user: wernull
github_show_profile_link: true
stackoverflow_user_id: 2653693

google_analytics_tracking_id: "G-H0WG6R9HD2"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - v3/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README